import Head from "next/head";
import type { NextPage } from "next";

import Layout from "../src/components/shared/Layout";
import styles from "../styles/404.module.css";
import { Grid, Typography } from "@mui/material";

const Error404: NextPage = () => {
	const hasWindow = typeof window !== "undefined";

	return (
		<>
			<Head>
				<title>DeFi-Logic</title>
				<meta name="description" content="Generated by DeFi-Logic" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Layout>
					<Grid className={styles.main}>
						<div className={styles.background}>
							<Typography className={styles.links}>
								Oops ! Page not found
							</Typography>
						</div>
					</Grid>
				</Layout>
			</main>
		</>
	);
};

export default Error404;
